version: "3"

services:
  web:
    build: .
    ports:
      - "3333:3333"
    links:
      - dynamodb

  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: pass
      AWS_REGION: us-east-1
    ports:
      - "8000:8000"
      